# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "source" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
        ref: source
      - name: Build Jekyll site
        run: |
          set -xo pipefail
          rm -rf _site/*
          docker run --rm -v "$PWD:/srv/jekyll" --user $(id -u):$(id -g) -i Cubernet/cubernet.github.io:latest jekyll build
          cp CNAME _site/CNAME
      - name: Deploy
        if: github.ref == 'refs/heads/source'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -xo pipefail
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout master
          ls -Q | grep -v _site | xargs rm -rf
          mv _site/* .
          rm -rf _site
          rm -rf .jekyll-cache
          [[ -n "$(git status --porcelain)" ]] || exit 0
          git add .
          git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master

